service: product-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  memorySize: 128
  timeout: 10

functions:
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: api/products
          method: post
          cors: true
  getAllProducts:
    handler: handler.getAllProducts
    events:
      - http:
          path: api/products
          method: get
          cors: true
  getProductById:
    handler: handler.getProductById
    events:
      - http:
          path: api/products/{id}
          method: get
          cors: true
  updateProductById:
    handler: handler.updateProduct
    events:
      - http:
          path: api/products/{id}
          method: put
          cors: true
  deleteProductById:
    handler: handler.deleteProduct
    events:
      - http:
          path: api/products/{id}
          method: delete
          cors: true

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
