service: product-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  memorySize: 128
  timeout: 10
  environment:
    PRODUCTS_TABLE: products

functions:
  createProduct:
    handler: controllers/productController/createProduct.handler
    events:
      - httpApi:
          path: /api/products
          method: post
          cors: true

  getAllProducts:
    handler: controllers/productController/getAllProducts.handler
    events:
      - httpApi:
          path: /api/products
          method: get
          cors: true

  getProductById:
    handler: controllers/productController/getProductById.handler
    events:
      - httpApi:
          path: /api/products/{id}
          method: get
          cors: true

  updateProductById:
    handler: controllers/productController/updateProduct.handler
    events:
      - httpApi:
          path: /api/products/{id}
          method: put
          cors: true

  deleteProductById:
    handler: controllers/productController/deleteProduct.handler
    events:
      - httpApi:
          path: /api/products/{id}
          method: delete
          cors: true

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
